#!/usr/bin/env python3

import rospy
from sensor_msgs.msg import CompressedImage
import cv2

import time

cam = None

image_pub = rospy.Publisher('/camera/image/compressed', CompressedImage, queue_size=10)

def gather_img(_event):
    #print('reading')
    _, img = cam.read()
    if img is not None:
        _, frame = cv2.imencode('.jpg', img)
        msg = CompressedImage()
        msg.data = frame.tobytes()
        image_pub.publish(msg)
    else:
        print('image is empty')
        

if __name__ == '__main__':
    # setup camera and resolution
    cam = cv2.VideoCapture(-1)
    cam.set(cv2.CAP_PROP_FRAME_WIDTH, 320)
    cam.set(cv2.CAP_PROP_FRAME_HEIGHT, 240)
    print('start sleep...')
    time.sleep(1.0)
    print('start ros...')
    rospy.init_node('otomo_camera')
    timer = rospy.Timer(rospy.Duration(0, 33e6), gather_img)
    print('go!')
    rospy.spin()

